name: Validate and push docker image
on:
  pull_request:
    paths:
      - 'db/**'
jobs:
  push-docker-image-dababase:
    runs-on: ubuntu-latest
    steps:
      - name: Obtain source code
        uses: actions/checkout@v4
      - name: Authenticate on Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./db
          file: ./db/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/contcode-hackatondb:latest
            ${{ secrets.DOCKER_USERNAME }}/contcode-hackatondb:v${{ github.run_number }}